# Generated by Django 5.2.5 on 2025-09-17 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, unique=True)),
                (
                    "polyp_pos_xywh",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "pathology_diagnosis",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("localization_label", models.IntegerField(default=-1)),
                ("size_label", models.IntegerField(default=-1)),
                ("cleanliness_label", models.IntegerField(default=-1)),
                ("overall", models.IntegerField(default=-1)),
                ("colonexpansion_label", models.IntegerField(default=-1)),
                ("img_cleanliness", models.IntegerField(default=-1)),
                ("img_overall", models.IntegerField(default=-1)),
                ("annotator_mail", models.CharField(default="none", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localization_label", models.IntegerField(default=-1)),
                ("size_label", models.IntegerField(default=-1)),
                ("cleanliness_label", models.IntegerField(default=-1)),
                ("overall", models.IntegerField(default=-1)),
                ("colonexpansion_label", models.IntegerField(default=-1)),
                ("img_cleanliness", models.IntegerField(default=-1)),
                ("img_overall", models.IntegerField(default=-1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="labeling.imageitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("image", "user")},
            },
        ),
    ]
