# Generated by Django 5.2.5 on 2025-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageitem",
            name="is_cut",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imageitem",
            name="is_polyp",
            field=models.BooleanField(default=True),
        ),
    ]
