# Generated by Django 5.2.5 on 2025-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeling", "0002_imageitem_is_cut_imageitem_is_polyp"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageitem",
            name="img_file_prefix",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="imageitem",
            name="patient_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="imageitem",
            name="polyp_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="imageitem",
            name="path",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name="imageitem",
            unique_together={("patient_id", "polyp_id", "img_file_prefix")},
        ),
    ]
